
version: '3.3'

services:
    DB:
        image: mariadb:latest
        container_name: mysql_host
        restart: always
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: MaxAriel@1618
            MYSQL_DATABASE: database_host
            MYSQL_USER: MaxAriel
            MYSQL_PASSWORD: MaxAriel@1618

    web:
        image: php:7.3.26-apache
        container_name: php_host
        restart: always
        volumes:
            - /var/www/html:/var/www/html
        ports:
            - 6300:80
        depends_on:
            - DB





