

---
version: '3'

services:
    docker-registry:
        container_name: my-registry
        image: registry:2
        ports:
            - 4001:5000
        restart: always
        volumes:
            - ./volume:/var/lib/registry
    docker-registry-ui:
        container_name: registry-ui
        image: joxit/docker-registry-ui:static
        ports:
            - 8080:80
        environment:
            ENV_DOCKER_REGISTRY_HOST: my-registry
            ENV_DOCKER_REGISTRY_PORT: 5000




https://www.youtube.com/watch?v=8gEs_zefNYA




docker-compose -f Docker_registry.yaml up
