
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: webapp-c
    image: nginx:alpine
    volumeMounts:
    - name: data
      mountPath: /var/www/html
  
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: local-pvc
      
      
kind: PersistentVolume
apiVersion: v1
metadata:
   name: pv-log
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/log
    type: DirectoryOrCreate
    
    
    
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: local-pvc 
spec:
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
        storage: 500Mi
   storageClassName: local-storage
