
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: nautilus
  labels:
    name:  time-check
spec:
  volumes:
  - name: log-volume
    emptyDir: {}
  containers:
  - name: time-check
    image: busybox:latest
    resources: {}
    envFrom:
      - configMapRef:
          name: time-config
    command: ["/bin/sh"]
    args: ["-c", "while true; do date; sleep $TIME_FREQ;done >> /opt/finance/time/time-check.log"]
    volumeMounts:
    - name: log-volume
      mountPath: /opt/sysops/time
    
  





apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: nautilus
data:
  TIME_FREQ: "4"








	RESUME

The Nautilus DevOps team want to create a time check pod in a particular Kubernetes namespace and record the logs. This might be initially used only for existing purposes, but later can be implemented in an existing cluster. Please find more details below about the task and perform it.


Create a pod called time-check in the datacenter namespace. This pod should run a container called time-check container should use the busybox image with latest tag only and remember to mention tag i.e busybox:latest.

Create a config map called time-config with the data TIME_FREQ=9 in the same namespace, and volume name should be log-volume.

The time-check container should run the command: while true; do date; sleep $TIME_FREQ;done and should write the result to the location /opt/finance/time/time-check.log.

3.The path /opt/finance/time on the pod should mount a volume that lasts the lifetime of this pod.

Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.