
apiVersion: v1
kind: Pod
metadata: 
  name: volume-share-devops
spec:
  volumes:
  - name: volume-share
    emptyDir: {}

  containers:
  - name: volume-container-devops-1
    image: centos:latest
    command: ['/bin/bash', '-c', 'sleep 10000']
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/official 
  - name: volume-container-devops-2
    image: centos:latest
    command: ['/bin/bash', '-c', 'sleep 10000']
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/games



kubectl exec -it POD_name --container Container_name -- /bin/bash