

kubectl create secret generic beta --from-file=/opt/beta.txt


apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
spec:
  containers:
  - name: secret-container-xfusion
    image: centos:latest
    volumeMounts:
    - name: secret-volume-xfusion
      mountPath: "/opt/games"
      readOnly: true
    command: ['/bin/bash', '-c', 'sleep 10000']
    
  volumes:
  - name: secret-volume-xfusion
    secret:
      secretName: beta
      
      
      
      
	RESUME

The Nautilus DevOps team is working to deploy some tools in Kubernetes cluster. Some of the tools are licence based so that licence information needs to be stored securely within Kubernetes cluster. Therefore, the team wants to utilize Kubernetes secrets to store those secrets. Below you can find more details about the requirements:


We already have a secret key file blog.txt under /opt location on jump host. Create a secret named as blog and it should contain the password/license-number present in blog.txt file.

Also create a pod named secret-xfusion.

Configure pod's spec as container name should be secret-container-xfusion, image should be debian preferably with latest tag (remember to mention the tag with image). Use command '/bin/bash', '-c' and 'sleep 10000' for container. Mount a volume named as secret-volume-xfusion. The mount path should be /opt/games and mode should be readOnly.

Mount the secret within this volume.

To verify you can exec into the container secret-container-xfusion, to check the secret key under the mounted path /opt/games.

Secret type should be generic.

Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.
