
			ASSIGNER UN LABEL À UN NOEUD
			
kubectl label node <NODE_NAME> <key>=<value>

kubectl label node node01 color=red

.....................................................................................

apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    app: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: In
            values:
            - red 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
