
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devops
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/finance"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: pvc-devops
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteOnce
   resources:
      requests:
        storage: 2Gi
---        
apiVersion: v1
kind: Pod
metadata:
  name: pod-devops
spec:
  containers:
  - name: container-devops
    image: nginx:latest
    volumeMounts:
    - name: storage-devops
      mountPath: "/usr/share/nginx/html"
    ports:
      - containerPort: 80
      
  volumes:
  - name: storage-devops
    persistentVolumeClaim:
      claimName: pvc-devops
      
      
      
      kubectl describe po <pod-name>
      
      kubectl exec -it nom-du-pod - cat /log/app.log
