



kubectl exec -ti ubuntu-sleeper /bin/bash


apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  securityContext:
    runAsUser: 1010
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    
    
    
    

---L'ID utilisateur défini dans le securityContext du conteneur remplace l'ID utilisateur dans le POD

---The User ID defined in the securityContext of the POD is carried over to all the PODs in the container.




apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: ubuntu
    name: ubuntu-sleeper
    securityContext:
      capabilities:
        add: ["SYS_TIME"]
