
---

- hosts: all
  become: true
 
  tasks:

  - name: copy file to stapp02
    copy:
      src: /usr/src/finance/blog.txt
      dest: /opt/finance/blog.txt
      owner: tony
      group: tony
      mode: '0644'
    when: ansible_hostname == "stapp01"
  - name: copy file to stapp02
    copy:
      src: /usr/src/finance/story.txt
      dest: /opt/finance/story.txt
      owner: steve
      group: steve
      mode: '0644'
    when: ansible_hostname == "stapp02"
  - name: copy file to stapp02
    copy:
      src: /usr/src/finance/media.txt
      dest: /opt/finance/media.txt
      owner: banner
      group: banner
      mode: '0644'
    when: ansible_hostname == "stapp03"
